# Generated by Django 5.0.4 on 2024-04-13 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polihack_site', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='user',
        ),
    ]
