# Generated by Django 5.0.4 on 2024-04-13 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polihack_site', '0002_remove_subject_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='polihack_site.userdata'),
        ),
    ]
